# Generated by Django 6.0.6 on 2026-07-01 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta de crédito/débito')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto en soles (S/)', max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=10)),
                ('referencia', models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
