# Generated by Django 6.0.6 on 2026-07-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='viajes.viaje'),
        ),
    ]
