# Generated by Django 6.0.6 on 2026-07-01 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_direccion', models.CharField(max_length=255)),
                ('origen_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origen_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destino_direccion', models.CharField(max_length=255)),
                ('destino_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destino_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_estimado_min', models.PositiveIntegerField()),
                ('modo_tarifa', models.CharField(choices=[('automatica', 'Tarifa automática'), ('oferta', 'El pasajero propone la tarifa')], default='automatica', max_length=15)),
                ('tarifa_sugerida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarifa_propuesta_pasajero', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tarifa_final', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('buscando', 'Buscando conductor'), ('aceptado', 'Conductor asignado'), ('en_camino_recojo', 'Conductor en camino al recojo'), ('en_curso', 'Viaje en curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='buscando', max_length=20)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=7)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=100)),
                ('color_vehiculo', models.CharField(blank=True, max_length=30)),
                ('emergencia_activada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('hora_aceptado', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_conductor', to=settings.AUTH_USER_MODEL)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_pasajero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CompartirViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compartir', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ofertado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='viajes.viaje')),
            ],
            options={
                'ordering': ['monto_ofertado'],
                'unique_together': {('viaje', 'conductor')},
            },
        ),
    ]
