# Generated by Django 6.0.6 on 2026-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
