# Generated by Django 6.0.6 on 2026-07-01 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('economico', 'Económico'), ('confort', 'Confort'), ('van', 'Van / Grupo grande'), ('moto', 'Moto taxi')], default='economico', max_length=15)),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Ingresa una placa peruana valida, ej: ABC-123 (sin guion).', regex='^[A-Z0-9]{6,7}$')])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('soat_numero', models.CharField(max_length=30, verbose_name='N° de poliza SOAT')),
                ('soat_vencimiento', models.DateField()),
                ('soat_foto', models.ImageField(blank=True, null=True, upload_to='documentos/soat/')),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
