# Generated by Django 6.0.6 on 2026-07-01 17:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('pasajero', 'Pasajero'), ('conductor', 'Conductor'), ('admin', 'Administrador')], default='pasajero', max_length=15)),
                ('celular', models.CharField(blank=True, help_text='Numero de celular peruano (9 digitos).', max_length=9, validators=[django.core.validators.RegexValidator(message='Ingresa un numero de celular peruano valido (9 digitos, empieza con 9).', regex='^9\\d{8}$')])),
                ('dni', models.CharField(blank=True, max_length=8, verbose_name='DNI')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('celular_verificado', models.BooleanField(default=False)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('cuenta_bloqueada', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoConfianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingresa un numero de celular peruano valido (9 digitos, empieza con 9).', regex='^9\\d{8}$')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_confianza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto de confianza',
                'verbose_name_plural': 'Contactos de confianza',
            },
        ),
        migrations.CreateModel(
            name='PerfilConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_numero', models.CharField(max_length=20, verbose_name='N° de licencia de conducir')),
                ('licencia_foto', models.ImageField(blank=True, null=True, upload_to='documentos/licencias/')),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('antecedentes_foto', models.ImageField(blank=True, null=True, upload_to='documentos/antecedentes/', verbose_name='Certificado de antecedentes penales/policiales')),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente de revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('disponible', models.BooleanField(default=False, help_text='El conductor esta en linea y disponible')),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_viajes', models.PositiveIntegerField(default=0)),
                ('saldo_ganancias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
