# Generated by Django 6.0.6 on 2026-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_staff', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('duda', 'Duda general'), ('objeto_perdido', 'Objeto perdido'), ('reembolso', 'Reembolso'), ('queja', 'Queja sobre un viaje'), ('otro', 'Otro')], default='duda', max_length=20)),
                ('asunto', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket de soporte',
                'verbose_name_plural': 'Tickets de soporte',
                'ordering': ['-actualizado'],
            },
        ),
    ]
