# Generated by Django 6.0.6 on 2026-07-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_hechas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='viajes.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('viaje', 'autor')},
        ),
    ]
